<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE addressbook [
    <!ELEMENT addressbook (register*)>
    <!ELEMENT register (name, address, phone, email*, company)>
        <!ELEMENT name (first, last) >
            <!ELEMENT first (#PCDATA) >
            <!ELEMENT last (#PCDATA) >
        <!ELEMENT address (street, no, zip, country) >
            <!ELEMENT street (#PCDATA) >
            <!ELEMENT no (#PCDATA) >
            <!ELEMENT zip (#PCDATA) >
            <!ELEMENT country (#PCDATA) >
        <!ELEMENT phone (#PCDATA) >
        <!ELEMENT email (#PCDATA) >
        <!ELEMENT company (companyname, website) >
            <!ELEMENT companyname (#PCDATA) >
            <!ELEMENT website (#PCDATA) >
]>

<addressbook>
    <register>
       <name>
          <first>Jennifer</first>
          <last>Lopez</last>
       </name>
       <address>
          <street>Wall Street</street>
          <no>1</no>
          <zip>112233</zip>
          <country>United States</country>
       </address>
       <phone>666555444</phone>
       <email>jennifer@email.com</email>
       <company>
          <companyname>Musical Studios</companyname>
          <website>musicalstudios.com</website>
       </company>
    </register>
    <register>
       <name>
          <first>Gerard</first>
          <last>Way</last>
       </name>
       <address>
          <street>The Black Parade</street>
          <no>99</no>
          <zip>332211</zip>
          <country>Canada</country>
       </address>
       <phone>665544332</phone>
       <email>gerard@email.com</email>
       <company>
          <companyname>Rock and Roll Studios</companyname>
          <website>rockandrollstudios.com</website>
       </company>
    </register>
</addressbook>